### ISSUE TITLE
Is it possible to deserialize errors?

### ISSUE THREAD

**Issue by mattwynne** [theogravity/new-error#6]
Hi,

I came across this library hunting for a way to serialize/deserialize custom errors for [passing over the wire](https://github.com/taskforcesh/bullmq/issues/254). It looks really well thought-out.

One thing I'm not clean on from reading the docs is if there's a way to deserialize one of these custom errors. It looks like the constructor methods `Registry#newError` and `#newBareError` don't look like they would work.

**Comment by theogravity** [comment]
Thanks for the comment. It was based off my work at Samsung trying to develop an error infrastructure that was both suitable for REST APIs and gRPC that can be consumed by fluentd and clients that called them.

Deserialization was built for that one, but it was rarely used. Let me see if it's possible here along with examples.

**Comment by theogravity** [comment]
It's in. See readme for more details.

**Comment by mattwynne** [comment]
Thankyou!!!
